x-airflow-common:
  build: &id001
    network: host
    context: .
    dockerfile: Dockerfile
  environment: &id002
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
    PYTHONPATH: /opt/airflow/impactu:/opt/airflow
  volumes: &id003
  - /home/ozapatam/impactu_airflow/dags:/opt/airflow/dags
  - /home/ozapatam/impactu_airflow:/opt/airflow/impactu
  - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
  - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
  - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
  - /home/ozapatam/impactu_airflow:/opt/airflow
  - ./connections.yaml:/opt/airflow/connections.yaml
  user: ${AIRFLOW_UID:-50000}:0
  depends_on: &id006
    redis: &id004
      condition: service_healthy
    postgres: &id005
      condition: service_healthy
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
    - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - airflow
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  redis:
    image: redis:7.2-bookworm
    expose:
    - 6379
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
  airflow-apiserver:
    build: *id001
    environment: *id002
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-init:
        condition: service_completed_successfully
    command: api-server
    ports:
    - 8080:8080
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - http://localhost:8080/api/v2/version
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  airflow-scheduler:
    build: *id001
    environment: *id002
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - http://localhost:8974/health
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  airflow-dag-processor:
    build: *id001
    environment: *id002
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-init:
        condition: service_completed_successfully
    command: dag-processor
    healthcheck:
      test:
      - CMD-SHELL
      - airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  airflow-worker:
    build: *id001
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
      AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
      PYTHONPATH: /opt/airflow/impactu:/opt/airflow
      DUMB_INIT_SETSID: '0'
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: celery worker
    healthcheck:
      test:
      - CMD-SHELL
      - celery --app airflow.providers.celery.executors.celery_executor.app inspect
        ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app
        inspect ping -d "celery@$${HOSTNAME}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  airflow-triggerer:
    build: *id001
    environment: *id002
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-init:
        condition: service_completed_successfully
    command: triggerer
    healthcheck:
      test:
      - CMD-SHELL
      - airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  airflow-init:
    build: *id001
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: ''
      AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
      PYTHONPATH: /opt/airflow/impactu:/opt/airflow
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    volumes: *id003
    user: 0:0
    depends_on: *id006
    entrypoint: /bin/bash
    command:
    - -c
    - "if [[ -z \"${AIRFLOW_UID}\" ]]; then\n  echo\n  echo -e \"\\033[1;33mWARNING!!!:\
      \ AIRFLOW_UID not set!\\e[0m\"\n  echo \"If you are on Linux, you SHOULD follow\
      \ the instructions below to set \"\n  echo \"AIRFLOW_UID environment variable,\
      \ otherwise files will be owned by root.\"\n  echo \"For other operating systems\
      \ you can get rid of the warning with manually created .env file:\"\n  echo\
      \ \"    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user\"\
      \n  echo\n  export AIRFLOW_UID=$$(id -u)\nfi\none_meg=1048576\nmem_available=$$(($$(getconf\
      \ _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))\ncpus_available=$$(grep -cE\
      \ 'cpu[0-9]+' /proc/stat)\ndisk_available=$$(df / | tail -1 | awk '{print $$4}')\n\
      warning_resources=\"false\"\nif (( mem_available < 4000 )) ; then\n  echo\n\
      \  echo -e \"\\033[1;33mWARNING!!!: Not enough memory available for Docker.\\\
      e[0m\"\n  echo \"At least 4GB of memory required. You have $$(numfmt --to iec\
      \ $$((mem_available * one_meg)))\"\n  echo\n  warning_resources=\"true\"\nfi\n\
      if (( cpus_available < 2 )); then\n  echo\n  echo -e \"\\033[1;33mWARNING!!!:\
      \ Not enough CPUS available for Docker.\\e[0m\"\n  echo \"At least 2 CPUs recommended.\
      \ You have $${cpus_available}\"\n  echo\n  warning_resources=\"true\"\nfi\n\
      if (( disk_available < one_meg * 10 )); then\n  echo\n  echo -e \"\\033[1;33mWARNING!!!:\
      \ Not enough Disk space available for Docker.\\e[0m\"\n  echo \"At least 10\
      \ GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))\"\
      \n  echo\n  warning_resources=\"true\"\nfi\nif [[ $${warning_resources} == \"\
      true\" ]]; then\n  echo\n  echo -e \"\\033[1;33mWARNING!!!: You have not enough\
      \ resources to run Airflow (see above)!\\e[0m\"\n  echo \"Please follow the\
      \ instructions to increase amount of resources available:\"\n  echo \"   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin\"\
      \n  echo\nfi\necho\necho \"Creating missing opt dirs if missing:\"\necho\nmkdir\
      \ -v -p /opt/airflow/{logs,dags,plugins,config}\necho\necho \"Airflow version:\"\
      \n/entrypoint airflow version\necho\necho \"Files in shared volumes:\"\necho\n\
      ls -la /opt/airflow/{logs,dags,plugins,config}\necho\necho \"Running airflow\
      \ config list to create default config file if missing.\"\necho\n/entrypoint\
      \ airflow config list >/dev/null\necho\necho \"Files in shared volumes:\"\n\
      echo\nls -la /opt/airflow/{logs,dags,plugins,config}\necho\necho \"Change ownership\
      \ of files in /opt/airflow to ${AIRFLOW_UID}:0\"\necho\nchown -R \"${AIRFLOW_UID}:0\"\
      \ /opt/airflow/\necho\necho \"Change ownership of files in shared volumes to\
      \ ${AIRFLOW_UID}:0\"\necho\nchown -v -R \"${AIRFLOW_UID}:0\" /opt/airflow/{logs,dags,plugins,config}\n\
      echo\necho \"Files in shared volumes:\"\necho\nls -la /opt/airflow/{logs,dags,plugins,config}\n\
      \n/entrypoint airflow connections import /opt/airflow/connections.yaml\n"
  airflow-cli:
    build: *id001
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
      AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
      PYTHONPATH: /opt/airflow/impactu:/opt/airflow
      CONNECTION_CHECK_MAX_COUNT: '0'
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
    profiles:
    - debug
    command:
    - bash
    - -c
    - airflow
  flower:
    build: *id001
    environment: *id002
    volumes: *id003
    user: ${AIRFLOW_UID:-50000}:0
    depends_on:
      redis: *id004
      postgres: *id005
      airflow-init:
        condition: service_completed_successfully
    command: celery flower
    profiles:
    - flower
    ports:
    - 5555:5555
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - http://localhost:5555/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
  mongodb:
    image: mongo:8.0.5
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_DATABASE=impactu
    restart: always
volumes:
  postgres-db-volume: null
